---
title: "Statistical modeling (STATS 720)"
bibliography: stats720.bib
---

<!-- from https://www.w3schools.com/css/css_table.asp -->
<style>
th, td {
   vertical-align: top;
   padding: 15px;
}
tr:nth-child(even) {background-color: #f2f2f2;} 
th {background-color: #ccccff;}
</style>

Last updated: `r format(Sys.time(), "%d %b %Y")`

---

Materials on this web page are **under construction** and **subject to change**

---

### Course meetings

- 2-3 Tues, 9:30-11:30 Thurs, location [REDACTED] (see Mosaic or ask)

### Misc info

- Textbooks:
   - none, but references will be listed: see [here](./books.html) for a list of useful books
- [Full course bibliography](stats720_bib.html)
- Expected preparation: basic probability and stats, hypothesis testing, linear and generalized linear regression
- Notes on [plagiarism/collaboration/attribution](./honesty.html)
- [Software notes](software.html)


### Where to find stuff

- [SpringerLink](https://libraryssl.lib.mcmaster.ca/libaccess/login.php?url=https%3a%2f%2flink.springer.com)

### Links

- Lecture recordings (TBA)
- [Piazza](https://piazza.com/mcmaster.ca/fall2024/stats720) (course forum/communications)
- [Course outline](stats720_f2024_outline.docx)
- [The back-end for this site](https://github.com/bbolker/stats720)
- [R style guide](./R_style.html)

## Communication

- instructor: [Ben Bolker](http://math.mcmaster.ca/~bolker/)
    - General questions (anything you don't consider private) are best asked in the appropriate channel on Teams
    - Otherwise e-mail to `bolker@mcmaster.ca` with "STATS 720" in the subject line; include your MacID in your message (if applicable) if not e-mailing from your McMaster e-mail account
	- office hours TBA
	- responses are **not** guaranteed within 24 hours of an assignment deadline; please plan ahead!

## Schedule

(subject to revision!)

```{r setup, echo=FALSE,message=FALSE,warning=FALSE, results="asis", eval=TRUE}
library(huxtable)
library(dplyr)
library(readr)

mk_url <- function(x) {
  ifelse(nchar(trimws(x))==0,x,
         sprintf("[%s](https://bbolker.github.io/stats720/%s.html)",
                 x,x))
}

invisible(read_csv("sched.csv", show_col_types = FALSE)
          |> mutate(across(start_date, \(x) format(x, "%d %b %Y")))
          |> rename(Week = "week", `Start date` = "start_date",
                    Topic = "topic", Assignments = "assignments")
          |> hux()
          |> print_html(max_width=1000)
)
```

## References

