#! /bin/bash
for i in intro lin_models unified GLMs ridge_mixed glmms mcmc gams optim; do
    for j in pdf html; do ## html docx pdf slides.html
    	make docs/notes/$i.$j
    done
    ## mv notes/$i.slides.html docs/notes  ## hack
done
